### ISSUE TITLE
Internal Server Error - /types/<type1>/[type2]

### ISSUE THREAD

**Issue by LassaInora** [Yarkis01/TyraDex#63]
# Informations
URL: https://tyradex-git-feat-dex-yarkis01.vercel.app/api/v1/types/<\type1>/[type2]

# Problème
Les données ne sont pas envoyé.

# Données actuelles
```json
{"message": "Internal Server Error"}
```

# Données souhaitées
La réponse JSON

**Comment by Yarkis01** [comment]
Corrigé, merci du signalement !
