### ISSUE TITLE
[DATA] Unifier les URL

### ISSUE THREAD

**Issue by LassaInora** [Yarkis01/TyraDex#64]
# Informations
URL: https://tyradex-git-feat-dex-yarkis01.vercel.app/api/v1/types/

# Problème
Actuellement les sprites de pokémons sont hébergé sur "https://raw.githubusercontent.com/Yarkis01/TyraDex/images/" alors que les sprites de types sont toujours hébergé sur "https://raw.githubusercontent.com/Yarkis01/PokeAPI/images/"

La mise en cache en devient donc assez pénible

# Données actuelles
```json
{
    "id":2,
    "name": {
        "fr":"Dragon", 
        "en":"Dragon", 
        "jp":"\u30c9\u30e9\u30b4\u30f3"
    },
    "sprites":"https://raw.githubusercontent.com/Yarkis01/PokeAPI/images/types/dragon.png",
    ...
}
```

# Données souhaitées
```json
{
    "id":2,
    "name": {
        "fr":"Dragon", 
        "en":"Dragon", 
        "jp":"\u30c9\u30e9\u30b4\u30f3"
    },
    "sprites":"https://raw.githubusercontent.com/Yarkis01/TyraDex/images/types/dragon.png",
    ...
}
```

**Comment by Yarkis01** [comment]
Oups, j'avais oublié d'effectuer le changement d'URL dans un fichier 😅
