### ISSUE TITLE
Probleme ID mélofée

### ISSUE THREAD

**Issue by Franswa56** [Yarkis01/TyraDex#65]
# Informations
URL: https://tyradex.vercel.app/api/v1/pokemon/melodelfe

# Problème
Petit problème d'ID au niveau de l'objet evolution de melodelfe (mélofée a l'id 36 au lieu de 35)

# Données actuelles
"evolution": {
        "pre": [
            {
                "pokedexId": 173,
                "name": "Mélo",
                "condition": "Bonheur"
            },
            {
                "pokedexId": 36,
                "name": "Mélofée",
                "condition": "Pierre Lune"
            }
        ],
        "next": null,
        "mega": null
    },

# Données souhaitées
"evolution": {
        "pre": [
            {
                "pokedexId": 173,
                "name": "Mélo",
                "condition": "Bonheur"
            },
            {
                "pokedexId": 35,
                "name": "Mélofée",
                "condition": "Pierre Lune"
            }
        ],
        "next": null,
        "mega": null
    },

J'en profite pour vous remercier pour cette super API, actuellement en train d'apprendre le dev web, tout est beaucoup plus facile et amusant quand on travail avec des pokémons ! 
Je vous mets le lien de mon app react c'est mon premier projet et cela a été possible grâce a vous ! (l'app est en mobile first, je n'ai pas encore fais la mise en page desktop.)
https://pokedex-app-five-omega.vercel.app/
si vous voyez ceci n'hesitez pas a me repondre ! merci et bonne soirée !

**Comment by Yarkis01** [comment]
👋🏻 Merci pour le signalement de l'erreur, cela est maintenant corrigé.
Je suis heureux de voir que l'API te permet d'avancer tout en t'amusant sur ton projet. Je te souhaite bon courage pour la suite de ton projet, et je serais ravi d'avoir des nouvelles.
