### ISSUE TITLE
get pokemons by type :  electric, fairy and dark not working

### ISSUE THREAD

**Issue by Gi-bo** [Yarkis01/TyraDex#69]
# Informations
URL: https://tyradex.tech/api/v1/types/4, https://tyradex.tech/api/v1/types/5, https://tyradex.tech/api/v1/types/16

# Problème
Décrivez brièvement le problème...
Le tableau associé à l'attribut "pokemons" est vide

# Données actuelles
```json
{
[]
}
```

# Données souhaitées
```json
{
[pokemon1, pokemon2, pokemon3...]
}
```

**Comment by Ashzuu** [comment]
Bonsoir,

Merci pour votre issue, je vous informe que cela a été fix.
En vous remerciant,

Ashz
